### Test the String Analyzer API
POST http://string_analyzer.test/api/strings
Content-Type: application/json

{
    "value": "madam"
}

### Get a specific analyzed string
GET http://string_analyzer.test/api/strings/madam

### Create / Analyze a String
POST http://string_analyzer.test/api/strings
Content-Type: application/json

{
    "value": "madam"
}

### Get All Strings with Filtering
GET http://string_analyzer.test/api/strings/madam

### Get all analyzed strings
GET http://string_analyzer.test/api/strings
Accept: application/json


### Filter: only palindromes
GET http://string_analyzer.test/api/strings?is_palindrome=true
Accept: application/json

### Filter: by minimum length
GET http://string_analyzer.test/api/strings?min_length=4
Accept: application/json

### Analyze "hello"
GET http://string_analyzer.test/api/strings/hello
Accept: application/json

### Analyze "racecar"
GET http://string_analyzer.test/api/strings/racecar
Accept: application/json

### Filter: combine filters
GET http://string_analyzer.test/api/strings?is_palindrome=true&min_length=4
Accept: application/json

### Test with multiple filters
GET http://string_analyzer.test/api/strings?is_palindrome=true&min_length=3&max_length=10&word_count=1&contains_character=a

### Test with multiple filters
GET http://string_analyzer.test/api/strings?is_palindrome=true

###  Delete an existing String
DELETE http://string_analyzer.test/api/strings/madam

###  Delete non-existent String
DELETE http://string_analyzer.test/api/strings/unknown

### Natural language filtering
GET http://string_analyzer.test/api/strings/filter-by-natural-language?query=all single word palindromic strings

### Filter palindromic single-word strings
GET http://string_analyzer.test/api/strings/filter-by-natural-language?query=all+single+word+palindromic+strings
Accept: application/json



